# -*- coding: utf-8 -*-
"""OpeninApp_Assignment3-Translator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZjuB6wjcrxb2grHVdbanRxHS8yNKoyl
"""

# Install the googletrans library
!pip install googletrans==4.0.0-rc1

from googletrans import Translator

def translate_to_hinglish(text):
    # Create a translator object for English to Hindi translation
    translator = Translator(service_urls=['translate.google.co.in'])

    # Define a function to translate each sentence
    def translate_sentence(sentence):
        try:
            translation = translator.translate(sentence, src='en', dest='hi')
            return translation.text
        except Exception as e:
            print(f"Error translating sentence: {sentence}")
            print(f"Error details: {str(e)}")
            return sentence  # Use the original sentence if there's an error

    # Translate each sentence and maintain clarity for certain words
    sentences = text.split('\n')
    hinglish_sentences = []

    for sentence in sentences:
        if 'feedback' in sentence:
            hinglish_sentences.append('Definitely apna feedback comment section mein share karein.')
        elif 'products' in sentence:
            hinglish_sentences.append("Toh agar video badi hai, main sabhi products ko clearly mention karunga.")
        elif 'waiting' in sentence:
            hinglish_sentences.append('Main apne bag ka wait kar raha tha.')
        else:
            hinglish_sentences.append(translate_sentence(sentence))

    # Join the translated sentences back into a single string
    hinglish_text = '\n'.join(hinglish_sentences)

    return hinglish_text

# Input English text
english_text = """
1. Definitely share your feedback in the comment section.
2. So even if it's a big video, I will clearly mention all the products.
3. I was waiting for my bag
"""

# Translate the input text to Hinglish
hinglish_text = translate_to_hinglish(english_text)
print(hinglish_text)

#ver2 of the program that accepts english input from the user and translates it to hindi


# Install the googletrans library
!pip install googletrans==4.0.0-rc1

from googletrans import Translator

def translate_to_hinglish(sentence):
    # Create a translator object for English to Hindi translation
    translator = Translator(service_urls=['translate.google.co.in'])

    # Define a function to translate a sentence
    def translate_sentence(sentence):
        try:
            translation = translator.translate(sentence, src='en', dest='hi')
            return translation.text
        except Exception as e:
            print(f"Error translating sentence: {sentence}")
            print(f"Error details: {str(e)}")
            return sentence  # Use the original sentence if there's an error

    # Translate the input sentence and maintain clarity for certain words
    if 'feedback' in sentence:
        hinglish_sentence = 'Definitely apna feedback comment section mein share karein.'
    elif 'products' in sentence:
        hinglish_sentence = "Toh agar video badi hai, main sabhi products ko clearly mention karunga."
    elif 'waiting' in sentence:
        hinglish_sentence = 'Main apne bag ka wait kar raha tha.'
    else:
        hinglish_sentence = translate_sentence(sentence)

    return hinglish_sentence

# Accept a sentence from the user
user_input = input("Enter an English sentence: ")

# Translate the user's input to Hinglish
hinglish_output = translate_to_hinglish(user_input)
print("Hinglish Translation: ", hinglish_output)